spring:
  application:
    name: fazendaesperanca
  jackson:
    time-zone: UTC
    locale: pt_BR
  datasource:
    url: jdbc:mysql://localhost:3306/fazendaesperanca?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: joj123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,httpexchanges
  endpoint:
    health:
      show-details: when_authorized

app:
  security:
    jwt:
      issuer: fazenda-esperanca
      access-token-ttl-minutes: 30
      refresh-token-ttl-days: 7
      secret: change-me-in-prod-please-32bytesmin
  storage:
    base-path: ./storage
    assinaturas-dir: assinaturas
    anexos-dir: anexos
  timezone: America/Sao_Paulo

cors:
  allowed-origins: http://localhost:3000,http://localhost:5173

---
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: classpath:db/migration,classpath:db/dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql:3306/fazendaesperanca?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
  storage:
    base-path: /data/storage

cors:
  allowed-origins: https://app.fazenda.org


